package com.pbani.service.impl;

import com.pbani.configuration.JwtProvider;
import com.pbani.domain.UserRole;
import com.pbani.exceptions.UserException;
import com.pbani.mapper.UserMapper;
import com.pbani.model.User;
import com.pbani.payload.dto.UserDto;
import com.pbani.payload.response.AuthResponse;
import com.pbani.repository.UserRepository;
import com.pbani.service.AuthService;
import lombok.RequiredArgsConstructor;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;
import java.util.Collection;

@Service



@RequiredArgsConstructor //No need to annotate with autowire whatever instance we create here
public class AuthServiceImpl implements AuthService {

    //final mens fields must be assigned a value after constructor finishes
    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtProvider jwtProvider;
    private final CustomUserServiceImplementation customUserServiceImplementation;

    /*
    because we have @RequiredArgsConstructor at the top of AuthServiceImpl.java we are essentially implementing this constructor:
            public AuthServiceImpl(UserRepository userRepository,
                           PasswordEncoder passwordEncoder,
                           JwtProvider jwtProvider, // <--- It's passed in here!
                           CustomUserServiceImplementation customUserServiceImplementation) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtProvider = jwtProvider; // <--- And stored here!
        this.customUserServiceImplementation = customUserServiceImplementation;

        constructor constructs an instance of AuthServiceImpl
    }


    */

    @Override
    public AuthResponse register(UserDto userDto) throws UserException {
        User user = userRepository.findByEmail(userDto.getEmail());
        if (user != null) {
            //added method signature in all method hierarchies
            throw new UserException("email already exists");
        }
        if(userDto.getRole().equals(UserRole.ROLE_ADMIN)) {
            throw new UserException("Admin role cannot be created manually");
        }

        /*
        these methods are automatically generated by lombok for the user model
        we have these defined ass private fields in User.java the user class is annotated with @Setter from the lombok library
        at compile-time Lombok sees the @Setter annotation and the lastLogin filed and generates the standard java setter method for me:
        Setter:
        public void setLastLogin(LocalDateTime lastLogin) {
            this.lastLogin = lastLogin;
            }

        Getter:
        public LocalDateTime getLastLogin() {
            return this.lastLogin;
            }
         */
        User newUser = new User();
        newUser.setEmail(userDto.getEmail());
        newUser.setPassword(passwordEncoder.encode(userDto.getPassword()));
        newUser.setRole(userDto.getRole());
        newUser.setFullName(userDto.getFullName());
        newUser.setPhone(userDto.getPhone());
        newUser.setLastLogin(LocalDateTime.now());
        newUser.setLastLogin(LocalDateTime.now());
        newUser.setCreatedAt(LocalDateTime.now());
        newUser.setUpdatedAt(LocalDateTime.now());

        User savedUser = userRepository.save(newUser);

        if (savedUser == null) {
            throw new UserException("Failed to save user to the database.");
        }

        Authentication authentication =
                new UsernamePasswordAuthenticationToken(userDto.getEmail(), userDto.getPassword());

        SecurityContextHolder.getContext().setAuthentication(authentication);

        //field used
        String jwt = jwtProvider.generateJwtToken(authentication);

        AuthResponse authResponse = new AuthResponse();
        authResponse.setJwt(jwt);
        authResponse.setMessage("registered successfully");
        authResponse.setUser(UserMapper.toDTO(savedUser));

        return authResponse;
    }

    @Override
    public AuthResponse login(UserDto userDto) throws UserException {
        String email = userDto.getEmail();
        String password = userDto.getPassword();
        Authentication authentication = authenticate(email, password);

        SecurityContextHolder.getContext().setAuthentication(authentication);

        Collection<? extends GrantedAuthority> authorities = authentication.getAuthorities();

        String role = authorities.iterator().next().getAuthority();

        String jwt = jwtProvider.generateJwtToken(authentication);

        User user = userRepository.findByEmail(email);

        user.setLastLogin(LocalDateTime.now());
        userRepository.save(user);

        AuthResponse authResponse = new AuthResponse();
        authResponse.setJwt(jwt);
        authResponse.setMessage("login successful");
        authResponse.setUser(UserMapper.toDTO(user));

        //return the jwt, message, and user this can then be sent to frontend as a JSON object
        return authResponse;
    }

    private Authentication authenticate(String email, String password) throws UserException {

        UserDetails userDetails = customUserServiceImplementation.loadUserByUsername(email);

        if (userDetails == null) {
            throw new UserException("email id doesn't exist " + email);
        }

        if (!passwordEncoder.matches(password, userDetails.getPassword())) {
            throw new UserException("incorrect password");
        }


        return new UsernamePasswordAuthenticationToken(userDetails, null, userDetails.getAuthorities());
    }
}
